Repository bc-compsci-club/bccs-club, pull requests merged in 2024-09, with the labels that each got.

#49 Build the resources page
  frontend/app/(portal)/resources/page.tsx
  frontend/app/layout.tsx
  frontend/app/ui/portal/homepage/HeroSection.tsx
  frontend/app/ui/portal/resources/FellowshipsSection.tsx
  frontend/app/ui/portal/resources/HeroSection.tsx
  frontend/app/ui/portal/resources/InternshipsSection.tsx
  frontend/app/ui/portal/resources/InterviewSection.tsx
  frontend/app/ui/portal/resources/StudentProgramsSection.tsx
Labels: feature

#54 Use Edge runtime instead of Node.js runtime for 404 page
  frontend/app/(portal)/[...not_found]/page.jsx
Labels: bugfix

#57 Build the events page and add Club Hours section
  frontend/app/(portal)/events/page.tsx
  frontend/app/ui/portal/contact/HeroSection.tsx
  frontend/app/ui/portal/events/ClubHours.tsx
  frontend/app/ui/portal/events/HeroSection.tsx
  frontend/app/ui/portal/homepage/EventsSection.tsx
  frontend/app/ui/portal/homepage/ResourcesSection.tsx
  frontend/app/ui/portal/resources/HeroSection.tsx
Labels: feature

#58 Add 404 page and Club Hours
  frontend/app/(portal)/[...not_found]/page.jsx
  frontend/app/(portal)/events/page.tsx
  frontend/app/not-found.tsx
  frontend/app/ui/portal/contact/HeroSection.tsx
  frontend/app/ui/portal/events/ClubHours.tsx
  frontend/app/ui/portal/events/HeroSection.tsx
  frontend/app/ui/portal/homepage/EventsSection.tsx
  frontend/app/ui/portal/homepage/ResourcesSection.tsx
  frontend/app/ui/portal/resources/HeroSection.tsx
Labels: feature

#65 Add Docker to run frontend (#64)
  docker-compose.yml
  frontend/Dockerfile
  frontend/README.md
Labels: feature

#66 Add docker to run frontend
  docker-compose.yml
  frontend/Dockerfile
  frontend/README.md
Labels: feature

#68 Add Final Round Ai mock interview to resources page (#67)
  frontend/app/ui/portal/resources/InterviewSection.tsx
Labels: enhancement

#69 Adding AI Mock Interview to Resources page- interview prep section #67
  frontend/app/ui/portal/resources/InterviewSection.tsx
Labels: enhancement

#70 Add Club Developers session
  frontend/app/(portal)/team/page.tsx
  frontend/app/images/team/club-developers/avatar.jpg
  frontend/app/ui/portal/team/ClubDevelopersSection.tsx
  frontend/app/ui/portal/team/ExecutiveBoardSection.tsx
Labels: enhancement
