Repository bc-compsci-club/bccs-club, pull requests merged in 2024-08, with the labels that each got.

#16 Create the home page (#11)
  .vscode/settings.json
  frontend/app/(portal)/contact/page.tsx
  frontend/app/(portal)/events/page.tsx
  frontend/app/(portal)/resources/page.tsx
  frontend/app/(portal)/team/page.tsx
  frontend/app/dashboard/page.tsx
  frontend/app/globals.css
  frontend/app/layout.tsx
  frontend/app/page.tsx
  frontend/app/ui/portal/footer.tsx
  frontend/app/ui/portal/homepage/EventsSection.tsx
  frontend/app/ui/portal/homepage/ResourcesSection.tsx
  frontend/app/ui/portal/homepage/TeamSection.tsx
  frontend/app/ui/portal/navbar.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/public/bccs-logo.png
  frontend/public/images/brooklyn-college/bc-library-16to9.jpg
  frontend/public/images/brooklyn-college/bc-library-4to3.jpg
  frontend/public/images/brooklyn-college/bc-view.jpg
  frontend/public/images/club-event/coffee-and-code-night.jpg
  frontend/public/images/club-event/company-visit.jpg
  frontend/public/images/club-event/professor-talk-16to9.jpg
  frontend/public/images/club-event/professor-talk-4to3.jpg
  frontend/public/images/club-event/project-sharing.jpg
  frontend/public/images/logo/club-logo-hd.png
  frontend/public/images/logo/club-logo-old.png
  frontend/public/images/logo/club-logo.png
  frontend/public/images/team/executive-board-2024-2025-01.jpg
  frontend/public/images/team/executive-board-2024-2025-02.jpg
Labels: feature

#17 Feature/homepage
  frontend/README.md
  frontend/app/images/brooklyn-college/bc-library-16to9.jpg
  frontend/app/images/brooklyn-college/bc-library-4to3.jpg
  frontend/app/images/brooklyn-college/bc-view.jpg
  frontend/app/images/club-event/coffee-and-code-night.jpg
  frontend/app/images/club-event/company-visit.jpg
  frontend/app/images/club-event/professor-talk-16to9.jpg
  frontend/app/images/club-event/professor-talk-4to3.jpg
  frontend/app/images/club-event/project-sharing.jpg
  frontend/app/images/logo/club-logo-hd.png
  frontend/app/images/logo/club-logo-old.png
  frontend/app/images/logo/club-logo.png
  frontend/app/images/team/executive-board-2024-2025-01.jpg
  frontend/app/images/team/executive-board-2024-2025-02.jpg
  frontend/app/page.tsx
  frontend/app/ui/portal/homepage/EventsSection.tsx
  frontend/app/ui/portal/homepage/ResourcesSection.tsx
  frontend/app/ui/portal/homepage/TeamSection.tsx
  frontend/app/ui/portal/navbar.tsx
  frontend/public/club-logo.png
  frontend/public/github-logo.svg
Labels: bugfix

#18 Dev
  .vscode/settings.json
  frontend/README.md
  frontend/app/(portal)/contact/page.tsx
  frontend/app/(portal)/events/page.tsx
  frontend/app/(portal)/resources/page.tsx
  frontend/app/(portal)/team/page.tsx
  frontend/app/dashboard/page.tsx
  frontend/app/globals.css
  frontend/app/images/brooklyn-college/bc-library-16to9.jpg
  frontend/app/images/brooklyn-college/bc-library-4to3.jpg
  frontend/app/images/brooklyn-college/bc-view.jpg
  frontend/app/images/club-event/coffee-and-code-night.jpg
  frontend/app/images/club-event/company-visit.jpg
  frontend/app/images/club-event/professor-talk-16to9.jpg
  frontend/app/images/club-event/professor-talk-4to3.jpg
  frontend/app/images/club-event/project-sharing.jpg
  frontend/app/images/logo/club-logo-hd.png
  frontend/app/images/logo/club-logo-old.png
  frontend/app/images/logo/club-logo.png
  frontend/app/images/team/executive-board-2024-2025-01.jpg
  frontend/app/images/team/executive-board-2024-2025-02.jpg
  frontend/app/layout.tsx
  frontend/app/page.tsx
  frontend/app/ui/portal/footer.tsx
  frontend/app/ui/portal/homepage/EventsSection.tsx
  frontend/app/ui/portal/homepage/ResourcesSection.tsx
  frontend/app/ui/portal/homepage/TeamSection.tsx
  frontend/app/ui/portal/navbar.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/public/bccs-logo.png
  frontend/public/club-logo.png
  frontend/public/github-logo.svg
Labels: feature

#19 Feature/team page
  frontend/app/(portal)/team/page.tsx
  frontend/app/images/logo/club-logo.png
  frontend/app/images/team/avatar.jpg
  frontend/app/images/team/megi-murati.jpg
  frontend/app/images/team/qingquan-li.jpg
  frontend/app/page.tsx
  frontend/app/ui/portal/footer.tsx
  frontend/app/ui/portal/homepage/EventsSection.tsx
  frontend/app/ui/portal/homepage/HeroSection.tsx
  frontend/app/ui/portal/homepage/ResourcesSection.tsx
  frontend/app/ui/portal/homepage/TeamSection.tsx
  frontend/app/ui/portal/navbar.tsx
  frontend/app/ui/portal/team/HeroSection.tsx
  frontend/app/ui/portal/team/MembersSection.tsx
  frontend/package-lock.json
  frontend/package.json
Labels: feature

#21 updated profile pic for Anna
  frontend/app/images/team/anna-belenko.jpg
  frontend/app/ui/portal/team/MembersSection.tsx
Labels: enhancement

#23 Update the Contributing Guidelines and make it clearer (#22)
  docs/CONTRIBUTING.md
Labels: documentation

#26 Update team page and documetation
  docs/CONTRIBUTING.md
  frontend/README.md
  frontend/app/images/team/excutive-board-2024-2025/anna-belenko.jpg
  frontend/app/images/team/excutive-board-2024-2025/executive-board-2024-2025-01.jpg
  frontend/app/images/team/excutive-board-2024-2025/executive-board-2024-2025-02.jpg
  frontend/app/images/team/excutive-board-2024-2025/faizan-khan.jpg
  frontend/app/images/team/excutive-board-2024-2025/kevin-liu.jpg
  frontend/app/images/team/excutive-board-2024-2025/megi-murati.jpg
  frontend/app/images/team/excutive-board-2024-2025/qingquan-li.jpg
  frontend/app/ui/portal/homepage/TeamSection.tsx
  frontend/app/ui/portal/team/MembersSection.tsx
Labels: enhancement

#27 Complete the team page - eboard section
  docs/CONTRIBUTING.md
  frontend/README.md
  frontend/app/(portal)/team/page.tsx
  frontend/app/images/logo/club-logo.png
  frontend/app/images/team/avatar.jpg
  frontend/app/images/team/excutive-board-2024-2025/anna-belenko.jpg
  frontend/app/images/team/excutive-board-2024-2025/executive-board-2024-2025-01.jpg
  frontend/app/images/team/excutive-board-2024-2025/executive-board-2024-2025-02.jpg
  frontend/app/images/team/excutive-board-2024-2025/faizan-khan.jpg
  frontend/app/images/team/excutive-board-2024-2025/kevin-liu.jpg
  frontend/app/images/team/excutive-board-2024-2025/megi-murati.jpg
  frontend/app/images/team/excutive-board-2024-2025/qingquan-li.jpg
  frontend/app/page.tsx
  frontend/app/ui/portal/footer.tsx
  frontend/app/ui/portal/homepage/EventsSection.tsx
  frontend/app/ui/portal/homepage/HeroSection.tsx
  frontend/app/ui/portal/homepage/ResourcesSection.tsx
  frontend/app/ui/portal/homepage/TeamSection.tsx
  frontend/app/ui/portal/navbar.tsx
  frontend/app/ui/portal/team/HeroSection.tsx
  frontend/app/ui/portal/team/MembersSection.tsx
  frontend/package-lock.json
  frontend/package.json
Labels: enhancement

#33 update button color
  frontend/app/ui/portal/homepage/HeroSection.tsx
  frontend/app/ui/portal/navbar.tsx
  frontend/tailwind.config.ts
Labels: enhancement

#36 update instagram link
  docs/CONTRIBUTING.md
  frontend/app/dashboard/page.tsx
  frontend/app/images/team/executive-board-2024-2025/anna-belenko.jpg
  frontend/app/images/team/executive-board-2024-2025/executive-board-2024-2025-01.jpg
  frontend/app/images/team/executive-board-2024-2025/executive-board-2024-2025-02.jpg
  frontend/app/images/team/executive-board-2024-2025/faizan-khan.jpg
  frontend/app/images/team/executive-board-2024-2025/kevin-liu.jpg
  frontend/app/images/team/executive-board-2024-2025/megi-murati.jpg
  frontend/app/images/team/executive-board-2024-2025/qingquan-li.jpg
  frontend/app/ui/portal/contact/HeroSection.tsx
  frontend/app/ui/portal/contact/SocialMediaSection.tsx
  frontend/app/ui/portal/footer.tsx
  frontend/app/ui/portal/homepage/EventsSection.tsx
  frontend/app/ui/portal/homepage/ResourcesSection.tsx
  frontend/app/ui/portal/homepage/TeamSection.tsx
  frontend/app/ui/portal/team/HeroSection.tsx
  frontend/app/ui/portal/team/MembersSection.tsx
Labels: enhancement

#37 Update buttons, social links, and fix typo
  docs/CONTRIBUTING.md
  frontend/app/dashboard/page.tsx
  frontend/app/images/team/executive-board-2024-2025/anna-belenko.jpg
  frontend/app/images/team/executive-board-2024-2025/executive-board-2024-2025-01.jpg
  frontend/app/images/team/executive-board-2024-2025/executive-board-2024-2025-02.jpg
  frontend/app/images/team/executive-board-2024-2025/faizan-khan.jpg
  frontend/app/images/team/executive-board-2024-2025/kevin-liu.jpg
  frontend/app/images/team/executive-board-2024-2025/megi-murati.jpg
  frontend/app/images/team/executive-board-2024-2025/qingquan-li.jpg
  frontend/app/ui/portal/contact/HeroSection.tsx
  frontend/app/ui/portal/contact/SocialMediaSection.tsx
  frontend/app/ui/portal/footer.tsx
  frontend/app/ui/portal/homepage/EventsSection.tsx
  frontend/app/ui/portal/homepage/HeroSection.tsx
  frontend/app/ui/portal/homepage/ResourcesSection.tsx
  frontend/app/ui/portal/homepage/TeamSection.tsx
  frontend/app/ui/portal/navbar.tsx
  frontend/app/ui/portal/team/HeroSection.tsx
  frontend/app/ui/portal/team/MembersSection.tsx
  frontend/tailwind.config.ts
Labels: enhancement

#39 Update Megi's profile
  frontend/app/ui/portal/team/MembersSection.tsx
Labels: enhancement

#40 Update Megi's Profile (GitHub link)
  frontend/app/ui/portal/team/MembersSection.tsx
Labels: enhancement

#46 Add WhatsApp link to the website footer and contact page
  frontend/app/ui/portal/contact/SocialMediaSection.tsx
  frontend/app/ui/portal/footer.tsx
Labels: enhancement
