Repository bc-compsci-club/bccs-club, pull requests merged in 2024-12, with the labels that each got.

#100 Create API endpoints for calendar envets
  .DS_Store
  .gitignore
  README.md
  api/.gitattributes
  api/.gitignore
  api/.mvn/wrapper/maven-wrapper.properties
  api/Dockerfile
  api/README.md
  api/docker-compose.yml
  api/mvnw
  api/mvnw.cmd
  api/pom.xml
  api/src/main/java/club/bccs/api/ApiApplication.java
  api/src/main/java/club/bccs/api/calendar/controller/EventController.java
  api/src/main/java/club/bccs/api/calendar/entity/Event.java
  api/src/main/java/club/bccs/api/calendar/repository/EventRepository.java
  api/src/main/java/club/bccs/api/calendar/service/EventService.java
  api/src/main/resources/application.properties
  api/src/test/java/club/bccs/api/ApiApplicationTests.java
  frontend/app/ui/portal/events/ClubHours.tsx
Labels: feature

#101 Config the deployment for API (backend)
  README.md
  api/Dockerfile
  api/README.md
  api/docker-compose.yml
  api/nginx-config.md
  api/pom.xml
  api/src/main/java/club/bccs/api/calendar/controller/EventController.java
  api/src/test/java/club/bccs/api/ApiApplicationTests.java
  api/src/test/resources/application-test.properties
  frontend/README.md
  frontend/docker-compose.yml
Labels: feature

#102 Create RESTful APIs for calendar events
  .DS_Store
  .gitignore
  README.md
  api/.gitattributes
  api/.gitignore
  api/.mvn/wrapper/maven-wrapper.properties
  api/Dockerfile
  api/README.md
  api/docker-compose.yml
  api/mvnw
  api/mvnw.cmd
  api/nginx-config.md
  api/pom.xml
  api/src/main/java/club/bccs/api/ApiApplication.java
  api/src/main/java/club/bccs/api/calendar/controller/EventController.java
  api/src/main/java/club/bccs/api/calendar/entity/Event.java
  api/src/main/java/club/bccs/api/calendar/repository/EventRepository.java
  api/src/main/java/club/bccs/api/calendar/service/EventService.java
  api/src/main/resources/application.properties
  api/src/test/java/club/bccs/api/ApiApplicationTests.java
  api/src/test/resources/application-test.properties
  frontend/README.md
  frontend/app/ui/portal/events/ClubHours.tsx
  frontend/docker-compose.yml
Labels: feature

#108 doc: Added MIT LICENSE
  docs/CONTRIBUTING.md
  docs/LICENSE.md
Labels: documentation

#109 Feature/api doc
  api/README.md
  api/pom.xml
  deployment/api-deployment/README.md
  deployment/api-deployment/docker-compose.dev.yml
Labels: documentation, feature

#110 Configure CORS (Cross-Origin Resource Sharing)
  api/src/main/java/club/bccs/api/config/CorsConfig.java
Labels: feature

#111 Add slug, update api endpoints with correct status codes
  api/src/main/java/club/bccs/api/calendar/controller/EventController.java
  api/src/main/java/club/bccs/api/calendar/entity/Event.java
  api/src/main/java/club/bccs/api/calendar/exception/GlobalExceptionHandler.java
  api/src/main/java/club/bccs/api/calendar/exception/ResourceNotFoundException.java
  api/src/main/java/club/bccs/api/calendar/repository/EventRepository.java
  api/src/main/java/club/bccs/api/calendar/service/EventService.java
  api/src/main/java/club/bccs/api/config/CorsConfig.java
  docs/database-operations.md
Labels: feature

#128 Schedule section for Game Jam page
  frontend/app/(portal)/game-jam-2025/page.tsx
  frontend/app/images/game-jam-2025-icons/jan16-icon.png
  frontend/app/images/game-jam-2025-icons/jan23-icon.png
  frontend/app/images/game-jam-2025-icons/jan24-icon.png
  frontend/app/ui/portal/game-jam-2025/Schedule.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/tsconfig.json
Labels: feature
