Repository bc-compsci-club/bccs-club, pull requests merged in 2024-10, with the labels that each got.

#71 Enhancement/add andrewli profile
  frontend/app/images/team/club-developers/andrew-li.jpg
  frontend/app/ui/portal/team/ClubDevelopersSection.tsx
Labels: enhancement

#74 Add Calendar Section to the Events Page
  frontend/app/(portal)/events/[event]/page.tsx
  frontend/app/(portal)/events/page.tsx
  frontend/app/ui/portal/events/CalendarSection.tsx
  frontend/app/ui/portal/events/EventSection.tsx
  frontend/package-lock.json
  frontend/package.json
Labels: feature

#75 Adding Club Developer Profile
  .DS_Store
  frontend/app/images/team/club-developers/ayesha-zaker.jpg
  frontend/app/ui/portal/team/ClubDevelopersSection.tsx
Labels: enhancement

#72 Enhancements/adding club developer
  frontend/app/images/team/club-developers/axel-mejia.jpg
  frontend/app/ui/portal/team/ClubDevelopersSection.tsx
Labels: enhancement

#77 Fix bug: personalWebsiteUrl-bug
  frontend/app/ui/portal/team/ClubDevelopersSection.tsx
Labels: bugfix

#79 update Club Coordinators section
  frontend/app/(portal)/team/page.tsx
  frontend/app/images/team/club-coordinators/andrew-li.jpg
  frontend/app/images/team/club-coordinators/avatar.jpg
  frontend/app/images/team/club-coordinators/axel-mejia.jpg
  frontend/app/images/team/club-coordinators/ayesha-zaker.jpg
  frontend/app/images/team/club-coordinators/nicole-shmerkin.jpg
  frontend/app/ui/portal/resources/FellowshipsSection.tsx
  frontend/app/ui/portal/resources/InternshipsSection.tsx
  frontend/app/ui/portal/team/ClubCoordinatorsSection.tsx
  frontend/app/ui/portal/team/ExecutiveBoardSection.tsx
Labels: enhancement

#80 Add Eboard Alumni section
  docs/CONTRIBUTING.md
  frontend/app/(portal)/team/page.tsx
  frontend/app/images/team/eboard-alumni/anastasia-gusenkov.jpg
  frontend/app/images/team/eboard-alumni/antara-khan.jpg
  frontend/app/images/team/eboard-alumni/avatar.jpg
  frontend/app/images/team/eboard-alumni/dennis-klimenkov.jpg
  frontend/app/images/team/eboard-alumni/diana-hung.jpg
  frontend/app/images/team/eboard-alumni/evelyn-velez.jpg
  frontend/app/images/team/eboard-alumni/gilman-huang.jpg
  frontend/app/images/team/eboard-alumni/junninho-thomas.jpg
  frontend/app/images/team/eboard-alumni/kevin-tam.jpg
  frontend/app/images/team/eboard-alumni/mariia-onokhina.jpg
  frontend/app/images/team/eboard-alumni/neissa-dorsinville.jpg
  frontend/app/images/team/eboard-alumni/oleksandra-kurbanova.jpg
  frontend/app/images/team/eboard-alumni/shahzoda-davlatova.jpg
  frontend/app/images/team/eboard-alumni/stephon-lawrence.jpg
  frontend/app/images/team/eboard-alumni/syeda-kazmi.jpg
  frontend/app/images/team/eboard-alumni/vincent-xie.jpg
  frontend/app/ui/portal/resources/FellowshipsSection.tsx
  frontend/app/ui/portal/team/EboardAlumniSection.tsx
Labels: feature

#81 Update team page and add a calendar to events page
  .DS_Store
  docs/CONTRIBUTING.md
  frontend/app/(portal)/events/[event]/page.tsx
  frontend/app/(portal)/events/page.tsx
  frontend/app/(portal)/team/page.tsx
  frontend/app/images/team/club-coordinators/andrew-li.jpg
  frontend/app/images/team/club-coordinators/avatar.jpg
  frontend/app/images/team/club-coordinators/axel-mejia.jpg
  frontend/app/images/team/club-coordinators/ayesha-zaker.jpg
  frontend/app/images/team/club-coordinators/nicole-shmerkin.jpg
  frontend/app/images/team/eboard-alumni/anastasia-gusenkov.jpg
  frontend/app/images/team/eboard-alumni/antara-khan.jpg
  frontend/app/images/team/eboard-alumni/avatar.jpg
  frontend/app/images/team/eboard-alumni/dennis-klimenkov.jpg
  frontend/app/images/team/eboard-alumni/diana-hung.jpg
  frontend/app/images/team/eboard-alumni/evelyn-velez.jpg
  frontend/app/images/team/eboard-alumni/gilman-huang.jpg
  frontend/app/images/team/eboard-alumni/junninho-thomas.jpg
  frontend/app/images/team/eboard-alumni/kevin-tam.jpg
  frontend/app/images/team/eboard-alumni/mariia-onokhina.jpg
  frontend/app/images/team/eboard-alumni/neissa-dorsinville.jpg
  frontend/app/images/team/eboard-alumni/oleksandra-kurbanova.jpg
  frontend/app/images/team/eboard-alumni/shahzoda-davlatova.jpg
  frontend/app/images/team/eboard-alumni/stephon-lawrence.jpg
  frontend/app/images/team/eboard-alumni/syeda-kazmi.jpg
  frontend/app/images/team/eboard-alumni/vincent-xie.jpg
  frontend/app/ui/portal/events/CalendarSection.tsx
  frontend/app/ui/portal/events/EventSection.tsx
  frontend/app/ui/portal/resources/FellowshipsSection.tsx
  frontend/app/ui/portal/resources/InternshipsSection.tsx
  frontend/app/ui/portal/team/ClubCoordinatorsSection.tsx
  frontend/app/ui/portal/team/EboardAlumniSection.tsx
  frontend/app/ui/portal/team/ExecutiveBoardSection.tsx
  frontend/package-lock.json
  frontend/package.json
Labels: feature

#85 Fix Overlapping Events in Event Calendar
  frontend/app/(portal)/events/page.tsx
  frontend/app/ui/portal/events/CalendarSection.tsx
  frontend/app/utils/types.ts
Labels: bugfix

#87 Update Event Calendar
  frontend/app/(portal)/events/page.tsx
Labels: enhancement
